// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucddezhjypzpiulyhfwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZGRlemhqeXB6cGl1bHloZndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTUwMDksImV4cCI6MjA2NTEzMTAwOX0.IqP0lXQl2QB11vs0_8HIxiSw8Ru0cYTzqvfjR8USD8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});